### ISSUE TITLE
Cannot run article-CRUD test after rebase from develop branch

### ISSUE THREAD

**Issue by coolbeatz71** [andela/ah-kgl-wakanda-backend#18]
Hey @gracelungu. Can you please, mind to fix bug in your test? Because we are not able to run test. 

This one is always failing
```
1) Article endpoints
       The endpoint to update an article
         Should update an article :

      Uncaught AssertionError: expected 500 to equal 200
      + expected - actual

      -500
      +200
```

I think the problem is not coming from your test, but from the way `npm script` are running and the `sequelize seeders`.

**Comment by coolbeatz71** [comment]
After console logging the error message from `server/helpers/errorhandler.js`
This is the response I am able to get from running test suites
```
The endpoint to update an article
 -------------: column Article.UserId does not exist
      1) "before each" hook
 -------------: column Article.UserId does not exist
```

**Comment by coolbeatz71** [comment]
After consoling the error captured inside the `catch block`of the method `update` which is inside `/controllers/articles.js` I am getting this error

```
e----------- : TypeError: Cannot read property 'length' of null
    at QueryInterface.bulkUpdate.then.affectedRows (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/sequelize/lib/model.js:3039:32)
    at tryCatcher (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mutombojean-vincent/Desktop/projects/ah-kgl-wakanda-backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5) 
```

**Comment by gracelungu** [comment]
The problem is due to the done() callback not being called right after assertions. This problem has been fixed. Thanks

**Comment by coolbeatz71** [comment]
@gracelungu, good job
